version: "3.8"

services:
  app:
    image: node-js
    container_name: app-node
    environment:
      MONGO_URL: "mongodb://db:27017/test"
    depends_on:
      - db
    ports:
      - "3000:3000"

  db:
    image: mongo
    container_name: mongo-db
