version: "3.8"

services:
  db:
    container_name: ${COMPOSE_PROJECT_NAME}-mongo-db
    image: mongo
  mysql:
    image: mysql:5.7
  app:
    container_name: ${COMPOSE_PROJECT_NAME}-app
    image: node-js
    depends_on:
      - db
      - mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    depends_on:
      - db
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      MYSQL_ROOT_PASSWORD: dbpass
      MYSQL_DATABASE: dbnode
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpass
    restart: always
    ports:
      - 8081:80
