version: "3.8"

services:
  app:
    build: .
    image: node-js
    environment:
      MONGO_URL: "mongodb://db:27017/test"
      UNA_VARIABLE: "Hola platzi!"
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src
      - /usr/src/node_modules
    command: npx nodemon --legacy-watch index.js

  db:
    image: mongo
